# Generated by Django 4.2.7 on 2023-11-13 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phones',
            fields=[
                ('id_phone', models.AutoField(primary_key=True, serialize=False)),
                ('producer', models.CharField(max_length=10)),
                ('model', models.CharField(max_length=25)),
                ('designation', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'Phones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Repairs',
            fields=[
                ('id_repair', models.AutoField(primary_key=True, serialize=False)),
                ('nr_case', models.CharField(max_length=9)),
                ('imei', models.BigIntegerField(default=0)),
                ('admission_date', models.DateField(verbose_name='data przyjęcia')),
                ('operator', models.CharField(max_length=15)),
                ('end_date', models.DateField(verbose_name='data zakonczenia')),
                ('status', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'Repairs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id_worker', models.AutoField(primary_key=True, serialize=False)),
                ('acronym', models.CharField(max_length=4)),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'Workers',
                'managed': False,
            },
        ),
    ]
